.PHONY: clean All

All:
	@echo "----------Building project:[ date - Debug ]----------"
	@"$(MAKE)" -f  "date.mk"
clean:
	@echo "----------Cleaning project:[ date - Debug ]----------"
	@"$(MAKE)" -f  "date.mk" clean
